In [1]:
!pip install optuna

Collecting optuna
  Downloading optuna-4.8.0-py3-none-any.whl.metadata (17 kB)
Requirement already satisfied: alembic>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from optuna) (1.18.4)
Collecting colorlog (from optuna)
  Downloading colorlog-6.10.1-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from optuna) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from optuna) (26.0)
Requirement already satisfied: sqlalchemy>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from optuna) (2.0.48)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from optuna) (4.67.3)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.12/dist-packages (from optuna) (6.0.3)
Requirement already satisfied: Mako in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna) (1.3.10)
Requirement already satisfied: typing-extensions>=4.12 in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna) (4.15.0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy>=1.4.2->optuna) (3.3.2)
Requirement already satisfied: MarkupSafe>=0.9.2 in /usr/local/lib/python3.12/dist-packages (from Mako->alembic>=1.5.0->optuna) (3.0.3)
Downloading optuna-4.8.0-py3-none-any.whl (419 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 419.5/419.5 kB 4.6 MB/s eta 0:00:00
Downloading colorlog-6.10.1-py3-none-any.whl (11 kB)
Installing collected packages: colorlog, optuna
Successfully installed colorlog-6.10.1 optuna-4.8.0

In [2]:
# Import necessary libraries
import optuna
from sklearn.datasets import load_diabetes
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# Load the Pima Indian Diabetes dataset from sklearn
# Note: Scikit-learn's built-in 'load_diabetes' is a regression dataset.
# We will load the actual diabetes dataset from an external source
import pandas as pd

# Load the Pima Indian Diabetes dataset (from UCI repository)
url = "https://raw.githubusercontent.com/jbrownlee/Datasets/master/pima-indians-diabetes.data.csv"
columns = ['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI',
           'DiabetesPedigreeFunction', 'Age', 'Outcome']

# Load the dataset
df = pd.read_csv(url, names=columns)

df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [3]:
import numpy as np

# Replace zero values with NaN in columns where zero is not a valid value
cols_with_missing_vals = ['Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI']
df[cols_with_missing_vals] = df[cols_with_missing_vals].replace(0, np.nan)

# Impute the missing values with the mean of the respective column
df.fillna(df.mean(), inplace=True)

# Check if there are any remaining missing values
print(df.isnull().sum())

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [4]:
# Split into features (X) and target (y)
X = df.drop('Outcome', axis=1)
y = df['Outcome']

# Split data into training and test sets (70% train, 30% test)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Optional: Scale the data for better model performance
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Check the shape of the data
print(f'Training set shape: {X_train.shape}')
print(f'Test set shape: {X_test.shape}')

Training set shape: (537, 8)
Test set shape: (231, 8)

In [5]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score

# Define the objective function
def objective(trial):
    # Suggest values for the hyperparameters
    n_estimators = trial.suggest_int('n_estimators', 50, 200)
    max_depth = trial.suggest_int('max_depth', 3, 20)

    # Create the RandomForestClassifier with suggested hyperparameters
    model = RandomForestClassifier(
        n_estimators=n_estimators,
        max_depth=max_depth,
        random_state=42
    )

    # Perform 3-fold cross-validation and calculate accuracy
    score = cross_val_score(model, X_train, y_train, cv=3, scoring='accuracy').mean()

    return score  # Return the accuracy score for Optuna to maximize

In [6]:
# Create a study object and optimize the objective function
study = optuna.create_study(direction='maximize', sampler=optuna.samplers.TPESampler())  # We aim to maximize accuracy
study.optimize(objective, n_trials=50)  # Run 50 trials to find the best hyperparameters

[I 2026-04-02 01:21:37,483] A new study created in memory with name: no-name-b59d4af3-1fdb-4214-916a-267fefd3adea
[I 2026-04-02 01:21:38,074] Trial 0 finished with value: 0.7560521415270017 and parameters: {'n_estimators': 97, 'max_depth': 6}. Best is trial 0 with value: 0.7560521415270017.
[I 2026-04-02 01:21:39,221] Trial 1 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 181, 'max_depth': 14}. Best is trial 1 with value: 0.7746741154562384.
[I 2026-04-02 01:21:39,998] Trial 2 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 128, 'max_depth': 8}. Best is trial 1 with value: 0.7746741154562384.
[I 2026-04-02 01:21:40,579] Trial 3 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 94, 'max_depth': 5}. Best is trial 1 with value: 0.7746741154562384.
[I 2026-04-02 01:21:41,230] Trial 4 finished with value: 0.7597765363128491 and parameters: {'n_estimators': 117, 'max_depth': 4}. Best is trial 1 with value: 0.7746741154562384.
[I 2026-04-02 01:21:41,730] Trial 5 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 79, 'max_depth': 20}. Best is trial 1 with value: 0.7746741154562384.
[I 2026-04-02 01:21:42,600] Trial 6 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 144, 'max_depth': 7}. Best is trial 1 with value: 0.7746741154562384.
[I 2026-04-02 01:21:43,351] Trial 7 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 121, 'max_depth': 17}. Best is trial 7 with value: 0.7783985102420856.
[I 2026-04-02 01:21:44,140] Trial 8 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 118, 'max_depth': 4}. Best is trial 7 with value: 0.7783985102420856.
[I 2026-04-02 01:21:44,715] Trial 9 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 53, 'max_depth': 9}. Best is trial 7 with value: 0.7783985102420856.
[I 2026-04-02 01:21:46,505] Trial 10 finished with value: 0.7783985102420857 and parameters: {'n_estimators': 171, 'max_depth': 16}. Best is trial 10 with value: 0.7783985102420857.
[I 2026-04-02 01:21:47,695] Trial 11 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 173, 'max_depth': 16}. Best is trial 10 with value: 0.7783985102420857.
[I 2026-04-02 01:21:48,942] Trial 12 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 199, 'max_depth': 18}. Best is trial 10 with value: 0.7783985102420857.
[I 2026-04-02 01:21:49,908] Trial 13 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 153, 'max_depth': 13}. Best is trial 10 with value: 0.7783985102420857.
[I 2026-04-02 01:21:50,851] Trial 14 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 154, 'max_depth': 16}. Best is trial 10 with value: 0.7783985102420857.
[I 2026-04-02 01:21:51,955] Trial 15 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 175, 'max_depth': 20}. Best is trial 10 with value: 0.7783985102420857.
[I 2026-04-02 01:21:52,750] Trial 16 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 132, 'max_depth': 11}. Best is trial 10 with value: 0.7783985102420857.
[I 2026-04-02 01:21:53,364] Trial 17 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 97, 'max_depth': 17}. Best is trial 10 with value: 0.7783985102420857.
[I 2026-04-02 01:21:54,372] Trial 18 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 162, 'max_depth': 14}. Best is trial 10 with value: 0.7783985102420857.
[I 2026-04-02 01:21:55,598] Trial 19 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 195, 'max_depth': 12}. Best is trial 10 with value: 0.7783985102420857.
[I 2026-04-02 01:21:55,963] Trial 20 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 58, 'max_depth': 18}. Best is trial 10 with value: 0.7783985102420857.
[I 2026-04-02 01:21:57,460] Trial 21 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 181, 'max_depth': 15}. Best is trial 10 with value: 0.7783985102420857.
[I 2026-04-02 01:21:59,546] Trial 22 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 187, 'max_depth': 11}. Best is trial 10 with value: 0.7783985102420857.
[I 2026-04-02 01:22:00,628] Trial 23 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 140, 'max_depth': 14}. Best is trial 10 with value: 0.7783985102420857.
[I 2026-04-02 01:22:01,746] Trial 24 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 169, 'max_depth': 18}. Best is trial 10 with value: 0.7783985102420857.
[I 2026-04-02 01:22:02,495] Trial 25 finished with value: 0.7821229050279329 and parameters: {'n_estimators': 117, 'max_depth': 15}. Best is trial 25 with value: 0.7821229050279329.
[I 2026-04-02 01:22:03,240] Trial 26 finished with value: 0.7783985102420857 and parameters: {'n_estimators': 119, 'max_depth': 16}. Best is trial 25 with value: 0.7821229050279329.
[I 2026-04-02 01:22:03,933] Trial 27 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 107, 'max_depth': 16}. Best is trial 25 with value: 0.7821229050279329.
[I 2026-04-02 01:22:04,412] Trial 28 finished with value: 0.756052141527002 and parameters: {'n_estimators': 73, 'max_depth': 10}. Best is trial 25 with value: 0.7821229050279329.
[I 2026-04-02 01:22:05,111] Trial 29 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 108, 'max_depth': 13}. Best is trial 25 with value: 0.7821229050279329.
[I 2026-04-02 01:22:05,649] Trial 30 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 82, 'max_depth': 19}. Best is trial 25 with value: 0.7821229050279329.
[I 2026-04-02 01:22:06,392] Trial 31 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 117, 'max_depth': 17}. Best is trial 25 with value: 0.7821229050279329.
[I 2026-04-02 01:22:07,303] Trial 32 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 141, 'max_depth': 15}. Best is trial 25 with value: 0.7821229050279329.
[I 2026-04-02 01:22:08,168] Trial 33 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 131, 'max_depth': 15}. Best is trial 25 with value: 0.7821229050279329.
[I 2026-04-02 01:22:08,871] Trial 34 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 107, 'max_depth': 17}. Best is trial 25 with value: 0.7821229050279329.
[I 2026-04-02 01:22:09,463] Trial 35 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 89, 'max_depth': 19}. Best is trial 25 with value: 0.7821229050279329.
[I 2026-04-02 01:22:10,633] Trial 36 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 121, 'max_depth': 14}. Best is trial 25 with value: 0.7821229050279329.
[I 2026-04-02 01:22:11,700] Trial 37 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 101, 'max_depth': 13}. Best is trial 25 with value: 0.7821229050279329.
[I 2026-04-02 01:22:13,012] Trial 38 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 150, 'max_depth': 16}. Best is trial 25 with value: 0.7821229050279329.
[I 2026-04-02 01:22:13,788] Trial 39 finished with value: 0.7765363128491619 and parameters: {'n_estimators': 126, 'max_depth': 19}. Best is trial 25 with value: 0.7821229050279329.
[I 2026-04-02 01:22:14,643] Trial 40 finished with value: 0.7746741154562383 and parameters: {'n_estimators': 135, 'max_depth': 15}. Best is trial 25 with value: 0.7821229050279329.
[I 2026-04-02 01:22:15,370] Trial 41 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 114, 'max_depth': 17}. Best is trial 25 with value: 0.7821229050279329.
[I 2026-04-02 01:22:16,154] Trial 42 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 122, 'max_depth': 17}. Best is trial 25 with value: 0.7821229050279329.
[I 2026-04-02 01:22:16,910] Trial 43 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 116, 'max_depth': 18}. Best is trial 25 with value: 0.7821229050279329.
[I 2026-04-02 01:22:17,503] Trial 44 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 91, 'max_depth': 16}. Best is trial 25 with value: 0.7821229050279329.
[I 2026-04-02 01:22:18,100] Trial 45 finished with value: 0.7579143389199254 and parameters: {'n_estimators': 113, 'max_depth': 3}. Best is trial 25 with value: 0.7821229050279329.
[I 2026-04-02 01:22:18,854] Trial 46 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 125, 'max_depth': 6}. Best is trial 25 with value: 0.7821229050279329.
[I 2026-04-02 01:22:19,725] Trial 47 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 136, 'max_depth': 20}. Best is trial 25 with value: 0.7821229050279329.
[I 2026-04-02 01:22:20,655] Trial 48 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 145, 'max_depth': 17}. Best is trial 25 with value: 0.7821229050279329.
[I 2026-04-02 01:22:21,306] Trial 49 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 101, 'max_depth': 12}. Best is trial 25 with value: 0.7821229050279329.

In [ ]:

# Print the best result
print(f'Best trial accuracy: {study.best_trial.value}')
print(f'Best hyperparameters: {study.best_trial.params}')

Best trial accuracy: 0.7802607076350093
Best hyperparameters: {'n_estimators': 113, 'max_depth': 18}

In [7]:
from sklearn.metrics import accuracy_score

# Train a RandomForestClassifier using the best hyperparameters from Optuna
best_model = RandomForestClassifier(**study.best_trial.params, random_state=42)

# Fit the model to the training data
best_model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = best_model.predict(X_test)

# Calculate the accuracy on the test set
test_accuracy = accuracy_score(y_test, y_pred)

# Print the test accuracy
print(f'Test Accuracy with best hyperparameters: {test_accuracy:.2f}')

Test Accuracy with best hyperparameters: 0.75

## Samplers in Optuna

In [8]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score

# Define the objective function
def objective(trial):
    # Suggest values for the hyperparameters
    n_estimators = trial.suggest_int('n_estimators', 50, 200)
    max_depth = trial.suggest_int('max_depth', 3, 20)

    # Create the RandomForestClassifier with suggested hyperparameters
    model = RandomForestClassifier(
        n_estimators=n_estimators,
        max_depth=max_depth,
        random_state=42
    )

    # Perform 3-fold cross-validation and calculate accuracy
    score = cross_val_score(model, X_train, y_train, cv=3, scoring='accuracy').mean()

    return score  # Return the accuracy score for Optuna to maximize

In [9]:
study = optuna.create_study(direction='maximize', sampler=optuna.samplers.RandomSampler())  # We aim to maximize accuracy
study.optimize(objective, n_trials=50)  # Run 50 trials to find the best hyperparameters

[I 2026-04-02 01:27:07,149] A new study created in memory with name: no-name-a273e310-f7bf-4652-951f-1dae3d7c1aab
[I 2026-04-02 01:27:09,209] Trial 0 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 195, 'max_depth': 16}. Best is trial 0 with value: 0.7783985102420856.
[I 2026-04-02 01:27:10,407] Trial 1 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 190, 'max_depth': 19}. Best is trial 0 with value: 0.7783985102420856.
[I 2026-04-02 01:27:11,103] Trial 2 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 109, 'max_depth': 20}. Best is trial 0 with value: 0.7783985102420856.
[I 2026-04-02 01:27:11,592] Trial 3 finished with value: 0.7783985102420857 and parameters: {'n_estimators': 74, 'max_depth': 18}. Best is trial 3 with value: 0.7783985102420857.
[I 2026-04-02 01:27:12,701] Trial 4 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 176, 'max_depth': 19}. Best is trial 3 with value: 0.7783985102420857.
[I 2026-04-02 01:27:13,797] Trial 5 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 192, 'max_depth': 5}. Best is trial 3 with value: 0.7783985102420857.
[I 2026-04-02 01:27:14,142] Trial 6 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 52, 'max_depth': 18}. Best is trial 3 with value: 0.7783985102420857.
[I 2026-04-02 01:27:14,874] Trial 7 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 121, 'max_depth': 6}. Best is trial 3 with value: 0.7783985102420857.
[I 2026-04-02 01:27:15,688] Trial 8 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 131, 'max_depth': 11}. Best is trial 3 with value: 0.7783985102420857.
[I 2026-04-02 01:27:16,433] Trial 9 finished with value: 0.7821229050279329 and parameters: {'n_estimators': 119, 'max_depth': 19}. Best is trial 9 with value: 0.7821229050279329.
[I 2026-04-02 01:27:17,024] Trial 10 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 102, 'max_depth': 5}. Best is trial 9 with value: 0.7821229050279329.
[I 2026-04-02 01:27:18,067] Trial 11 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 167, 'max_depth': 12}. Best is trial 9 with value: 0.7821229050279329.
[I 2026-04-02 01:27:19,100] Trial 12 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 175, 'max_depth': 5}. Best is trial 9 with value: 0.7821229050279329.
[I 2026-04-02 01:27:20,974] Trial 13 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 185, 'max_depth': 19}. Best is trial 9 with value: 0.7821229050279329.
[I 2026-04-02 01:27:22,379] Trial 14 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 170, 'max_depth': 6}. Best is trial 9 with value: 0.7821229050279329.
[I 2026-04-02 01:27:22,714] Trial 15 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 52, 'max_depth': 18}. Best is trial 9 with value: 0.7821229050279329.
[I 2026-04-02 01:27:23,626] Trial 16 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 148, 'max_depth': 10}. Best is trial 9 with value: 0.7821229050279329.
[I 2026-04-02 01:27:24,764] Trial 17 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 185, 'max_depth': 13}. Best is trial 9 with value: 0.7821229050279329.
[I 2026-04-02 01:27:25,670] Trial 18 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 157, 'max_depth': 6}. Best is trial 9 with value: 0.7821229050279329.
[I 2026-04-02 01:27:26,739] Trial 19 finished with value: 0.7597765363128491 and parameters: {'n_estimators': 182, 'max_depth': 6}. Best is trial 9 with value: 0.7821229050279329.
[I 2026-04-02 01:27:27,108] Trial 20 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 63, 'max_depth': 5}. Best is trial 9 with value: 0.7821229050279329.
[I 2026-04-02 01:27:27,963] Trial 21 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 143, 'max_depth': 8}. Best is trial 9 with value: 0.7821229050279329.
[I 2026-04-02 01:27:28,994] Trial 22 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 189, 'max_depth': 4}. Best is trial 9 with value: 0.7821229050279329.
[I 2026-04-02 01:27:29,904] Trial 23 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 148, 'max_depth': 18}. Best is trial 9 with value: 0.7821229050279329.
[I 2026-04-02 01:27:30,816] Trial 24 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 145, 'max_depth': 16}. Best is trial 9 with value: 0.7821229050279329.
[I 2026-04-02 01:27:31,163] Trial 25 finished with value: 0.7597765363128492 and parameters: {'n_estimators': 54, 'max_depth': 10}. Best is trial 9 with value: 0.7821229050279329.
[I 2026-04-02 01:27:32,552] Trial 26 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 186, 'max_depth': 12}. Best is trial 9 with value: 0.7821229050279329.
[I 2026-04-02 01:27:34,050] Trial 27 finished with value: 0.7597765363128491 and parameters: {'n_estimators': 159, 'max_depth': 6}. Best is trial 9 with value: 0.7821229050279329.
[I 2026-04-02 01:27:35,570] Trial 28 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 193, 'max_depth': 15}. Best is trial 9 with value: 0.7821229050279329.
[I 2026-04-02 01:27:36,327] Trial 29 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 123, 'max_depth': 10}. Best is trial 9 with value: 0.7821229050279329.
[I 2026-04-02 01:27:37,155] Trial 30 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 132, 'max_depth': 13}. Best is trial 9 with value: 0.7821229050279329.
[I 2026-04-02 01:27:37,926] Trial 31 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 125, 'max_depth': 9}. Best is trial 9 with value: 0.7821229050279329.
[I 2026-04-02 01:27:38,728] Trial 32 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 141, 'max_depth': 5}. Best is trial 9 with value: 0.7821229050279329.
[I 2026-04-02 01:27:39,155] Trial 33 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 66, 'max_depth': 11}. Best is trial 9 with value: 0.7821229050279329.
[I 2026-04-02 01:27:39,547] Trial 34 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 65, 'max_depth': 7}. Best is trial 9 with value: 0.7821229050279329.
[I 2026-04-02 01:27:40,350] Trial 35 finished with value: 0.7765363128491619 and parameters: {'n_estimators': 130, 'max_depth': 16}. Best is trial 9 with value: 0.7821229050279329.
[I 2026-04-02 01:27:41,254] Trial 36 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 145, 'max_depth': 19}. Best is trial 9 with value: 0.7821229050279329.
[I 2026-04-02 01:27:42,092] Trial 37 finished with value: 0.7765363128491619 and parameters: {'n_estimators': 135, 'max_depth': 18}. Best is trial 9 with value: 0.7821229050279329.
[I 2026-04-02 01:27:43,313] Trial 38 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 198, 'max_depth': 11}. Best is trial 9 with value: 0.7821229050279329.
[I 2026-04-02 01:27:44,240] Trial 39 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 145, 'max_depth': 16}. Best is trial 9 with value: 0.7821229050279329.
[I 2026-04-02 01:27:44,641] Trial 40 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 63, 'max_depth': 15}. Best is trial 9 with value: 0.7821229050279329.
[I 2026-04-02 01:27:45,636] Trial 41 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 106, 'max_depth': 16}. Best is trial 9 with value: 0.7821229050279329.
[I 2026-04-02 01:27:47,521] Trial 42 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 182, 'max_depth': 17}. Best is trial 9 with value: 0.7821229050279329.
[I 2026-04-02 01:27:48,648] Trial 43 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 172, 'max_depth': 7}. Best is trial 9 with value: 0.7821229050279329.
[I 2026-04-02 01:27:49,244] Trial 44 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 97, 'max_depth': 16}. Best is trial 9 with value: 0.7821229050279329.
[I 2026-04-02 01:27:49,762] Trial 45 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 81, 'max_depth': 12}. Best is trial 9 with value: 0.7821229050279329.
[I 2026-04-02 01:27:50,048] Trial 46 finished with value: 0.7560521415270017 and parameters: {'n_estimators': 54, 'max_depth': 3}. Best is trial 9 with value: 0.7821229050279329.
[I 2026-04-02 01:27:50,465] Trial 47 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 65, 'max_depth': 13}. Best is trial 9 with value: 0.7821229050279329.
[I 2026-04-02 01:27:51,660] Trial 48 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 195, 'max_depth': 9}. Best is trial 9 with value: 0.7821229050279329.
[I 2026-04-02 01:27:52,777] Trial 49 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 182, 'max_depth': 10}. Best is trial 9 with value: 0.7821229050279329.

In [10]:

# Print the best result
print(f'Best trial accuracy: {study.best_trial.value}')
print(f'Best hyperparameters: {study.best_trial.params}')

Best trial accuracy: 0.7821229050279329
Best hyperparameters: {'n_estimators': 119, 'max_depth': 19}

In [11]:
from sklearn.metrics import accuracy_score

# Train a RandomForestClassifier using the best hyperparameters from Optuna
best_model = RandomForestClassifier(**study.best_trial.params, random_state=42)

# Fit the model to the training data
best_model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = best_model.predict(X_test)

# Calculate the accuracy on the test set
test_accuracy = accuracy_score(y_test, y_pred)

# Print the test accuracy
print(f'Test Accuracy with best hyperparameters: {test_accuracy:.2f}')

Test Accuracy with best hyperparameters: 0.74

In [12]:
search_space = {
    'n_estimators': [50, 100, 150, 200],
    'max_depth': [5, 10, 15, 20]
}

In [13]:
# Create a study and optimize it using GridSampler
study = optuna.create_study(direction='maximize', sampler=optuna.samplers.GridSampler(search_space))
study.optimize(objective)

[I 2026-04-02 01:28:50,522] A new study created in memory with name: no-name-5e5653c9-bd9e-44f0-99ca-2ba43d5356fe
[I 2026-04-02 01:28:51,101] Trial 0 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 100, 'max_depth': 5}. Best is trial 0 with value: 0.7690875232774674.
[I 2026-04-02 01:28:52,026] Trial 1 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 150, 'max_depth': 10}. Best is trial 0 with value: 0.7690875232774674.
[I 2026-04-02 01:28:52,369] Trial 2 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 50, 'max_depth': 15}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-04-02 01:28:52,991] Trial 3 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 100, 'max_depth': 15}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-04-02 01:28:53,626] Trial 4 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 100, 'max_depth': 20}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-04-02 01:28:53,940] Trial 5 finished with value: 0.7579143389199254 and parameters: {'n_estimators': 50, 'max_depth': 10}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-04-02 01:28:54,776] Trial 6 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 150, 'max_depth': 5}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-04-02 01:28:55,714] Trial 7 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 150, 'max_depth': 20}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-04-02 01:28:56,653] Trial 8 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 150, 'max_depth': 15}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-04-02 01:28:58,569] Trial 9 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 200, 'max_depth': 10}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-04-02 01:29:00,281] Trial 10 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 200, 'max_depth': 20}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-04-02 01:29:01,555] Trial 11 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 200, 'max_depth': 15}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-04-02 01:29:02,680] Trial 12 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 200, 'max_depth': 5}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-04-02 01:29:02,994] Trial 13 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 50, 'max_depth': 5}. Best is trial 13 with value: 0.7746741154562384.
[I 2026-04-02 01:29:03,598] Trial 14 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 100, 'max_depth': 10}. Best is trial 13 with value: 0.7746741154562384.
[I 2026-04-02 01:29:03,937] Trial 15 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 50, 'max_depth': 20}. Best is trial 13 with value: 0.7746741154562384.

In [14]:

# Print the best result
print(f'Best trial accuracy: {study.best_trial.value}')
print(f'Best hyperparameters: {study.best_trial.params}')

Best trial accuracy: 0.7746741154562384
Best hyperparameters: {'n_estimators': 50, 'max_depth': 5}

In [15]:
from sklearn.metrics import accuracy_score

# Train a RandomForestClassifier using the best hyperparameters from Optuna
best_model = RandomForestClassifier(**study.best_trial.params, random_state=42)

# Fit the model to the training data
best_model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = best_model.predict(X_test)

# Calculate the accuracy on the test set
test_accuracy = accuracy_score(y_test, y_pred)

# Print the test accuracy
print(f'Test Accuracy with best hyperparameters: {test_accuracy:.2f}')

Test Accuracy with best hyperparameters: 0.74

## Optuna Visualizations

In [16]:
# For visualizations
from optuna.visualization import plot_optimization_history, plot_parallel_coordinate, plot_slice, plot_contour, plot_param_importances

In [17]:
# 1. Optimization History
plot_optimization_history(study).show()

In [18]:
# 2. Parallel Coordinates Plot
plot_parallel_coordinate(study).show()

In [19]:
# 3. Slice Plot
plot_slice(study).show()

In [20]:
# 4. Contour Plot
plot_contour(study).show()

In [21]:
# 5. Hyperparameter Importance
plot_param_importances(study).show()

## Optimizing Multiple ML Models

In [22]:
# Importing the required libraries
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.svm import SVC

In [23]:
# Define the objective function for Optuna
def objective(trial):
    # Choose the algorithm to tune
    classifier_name = trial.suggest_categorical('classifier', ['SVM', 'RandomForest', 'GradientBoosting'])

    if classifier_name == 'SVM':
        # SVM hyperparameters
        c = trial.suggest_float('C', 0.1, 100, log=True)
        kernel = trial.suggest_categorical('kernel', ['linear', 'rbf', 'poly', 'sigmoid'])
        gamma = trial.suggest_categorical('gamma', ['scale', 'auto'])

        model = SVC(C=c, kernel=kernel, gamma=gamma, random_state=42)

    elif classifier_name == 'RandomForest':
        # Random Forest hyperparameters
        n_estimators = trial.suggest_int('n_estimators', 50, 300)
        max_depth = trial.suggest_int('max_depth', 3, 20)
        min_samples_split = trial.suggest_int('min_samples_split', 2, 10)
        min_samples_leaf = trial.suggest_int('min_samples_leaf', 1, 10)
        bootstrap = trial.suggest_categorical('bootstrap', [True, False])

        model = RandomForestClassifier(
            n_estimators=n_estimators,
            max_depth=max_depth,
            min_samples_split=min_samples_split,
            min_samples_leaf=min_samples_leaf,
            bootstrap=bootstrap,
            random_state=42
        )

    elif classifier_name == 'GradientBoosting':
        # Gradient Boosting hyperparameters
        n_estimators = trial.suggest_int('n_estimators', 50, 300)
        learning_rate = trial.suggest_float('learning_rate', 0.01, 0.3, log=True)
        max_depth = trial.suggest_int('max_depth', 3, 20)
        min_samples_split = trial.suggest_int('min_samples_split', 2, 10)
        min_samples_leaf = trial.suggest_int('min_samples_leaf', 1, 10)

        model = GradientBoostingClassifier(
            n_estimators=n_estimators,
            learning_rate=learning_rate,
            max_depth=max_depth,
            min_samples_split=min_samples_split,
            min_samples_leaf=min_samples_leaf,
            random_state=42
        )

    # Perform cross-validation and return the mean accuracy
    score = cross_val_score(model, X_train, y_train, cv=3, scoring='accuracy').mean()
    return score

In [24]:
# Create a study and optimize it using CmaEsSampler
study = optuna.create_study(direction='maximize')
study.optimize(objective, n_trials=100)

[I 2026-04-02 01:29:07,383] A new study created in memory with name: no-name-be6303f3-f888-4fbb-8f0b-8009f3329610
[I 2026-04-02 01:29:08,243] Trial 0 finished with value: 0.7467411545623838 and parameters: {'classifier': 'RandomForest', 'n_estimators': 200, 'max_depth': 3, 'min_samples_split': 3, 'min_samples_leaf': 5, 'bootstrap': False}. Best is trial 0 with value: 0.7467411545623838.
[I 2026-04-02 01:29:08,277] Trial 1 finished with value: 0.6834264432029795 and parameters: {'classifier': 'SVM', 'C': 21.29585208111082, 'kernel': 'sigmoid', 'gamma': 'scale'}. Best is trial 0 with value: 0.7467411545623838.
[I 2026-04-02 01:29:09,111] Trial 2 finished with value: 0.7318435754189944 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 131, 'learning_rate': 0.1971085558074582, 'max_depth': 3, 'min_samples_split': 10, 'min_samples_leaf': 1}. Best is trial 0 with value: 0.7467411545623838.
[I 2026-04-02 01:29:09,590] Trial 3 finished with value: 0.7597765363128491 and parameters: {'classifier': 'RandomForest', 'n_estimators': 84, 'max_depth': 8, 'min_samples_split': 10, 'min_samples_leaf': 9, 'bootstrap': True}. Best is trial 3 with value: 0.7597765363128491.
[I 2026-04-02 01:29:09,627] Trial 4 finished with value: 0.7169459962756052 and parameters: {'classifier': 'SVM', 'C': 2.952071717025579, 'kernel': 'sigmoid', 'gamma': 'auto'}. Best is trial 3 with value: 0.7597765363128491.
[I 2026-04-02 01:29:09,761] Trial 5 finished with value: 0.6890130353817504 and parameters: {'classifier': 'SVM', 'C': 55.12073430492886, 'kernel': 'poly', 'gamma': 'auto'}. Best is trial 3 with value: 0.7597765363128491.
[I 2026-04-02 01:29:12,624] Trial 6 finished with value: 0.7690875232774674 and parameters: {'classifier': 'RandomForest', 'n_estimators': 296, 'max_depth': 16, 'min_samples_split': 8, 'min_samples_leaf': 5, 'bootstrap': True}. Best is trial 6 with value: 0.7690875232774674.
[I 2026-04-02 01:29:13,363] Trial 7 finished with value: 0.7467411545623838 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 51, 'learning_rate': 0.2304892595029741, 'max_depth': 8, 'min_samples_split': 6, 'min_samples_leaf': 5}. Best is trial 6 with value: 0.7690875232774674.
[I 2026-04-02 01:29:16,235] Trial 8 finished with value: 0.7523277467411545 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 261, 'learning_rate': 0.0756688364204435, 'max_depth': 6, 'min_samples_split': 9, 'min_samples_leaf': 5}. Best is trial 6 with value: 0.7690875232774674.
[I 2026-04-02 01:29:17,840] Trial 9 finished with value: 0.7616387337057727 and parameters: {'classifier': 'RandomForest', 'n_estimators': 290, 'max_depth': 13, 'min_samples_split': 5, 'min_samples_leaf': 8, 'bootstrap': True}. Best is trial 6 with value: 0.7690875232774674.
[I 2026-04-02 01:29:19,196] Trial 10 finished with value: 0.7709497206703911 and parameters: {'classifier': 'RandomForest', 'n_estimators': 221, 'max_depth': 20, 'min_samples_split': 7, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 10 with value: 0.7709497206703911.
[I 2026-04-02 01:29:20,585] Trial 11 finished with value: 0.7690875232774674 and parameters: {'classifier': 'RandomForest', 'n_estimators': 227, 'max_depth': 20, 'min_samples_split': 7, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 10 with value: 0.7709497206703911.
[I 2026-04-02 01:29:22,382] Trial 12 finished with value: 0.7690875232774674 and parameters: {'classifier': 'RandomForest', 'n_estimators': 300, 'max_depth': 19, 'min_samples_split': 8, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 10 with value: 0.7709497206703911.
[I 2026-04-02 01:29:23,791] Trial 13 finished with value: 0.7653631284916201 and parameters: {'classifier': 'RandomForest', 'n_estimators': 153, 'max_depth': 16, 'min_samples_split': 5, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 10 with value: 0.7709497206703911.
[I 2026-04-02 01:29:25,606] Trial 14 finished with value: 0.7728119180633147 and parameters: {'classifier': 'RandomForest', 'n_estimators': 238, 'max_depth': 16, 'min_samples_split': 8, 'min_samples_leaf': 7, 'bootstrap': False}. Best is trial 14 with value: 0.7728119180633147.
[I 2026-04-02 01:29:26,756] Trial 15 finished with value: 0.7709497206703911 and parameters: {'classifier': 'RandomForest', 'n_estimators': 230, 'max_depth': 16, 'min_samples_split': 7, 'min_samples_leaf': 7, 'bootstrap': False}. Best is trial 14 with value: 0.7728119180633147.
[I 2026-04-02 01:29:27,690] Trial 16 finished with value: 0.7728119180633147 and parameters: {'classifier': 'RandomForest', 'n_estimators': 192, 'max_depth': 13, 'min_samples_split': 2, 'min_samples_leaf': 10, 'bootstrap': False}. Best is trial 14 with value: 0.7728119180633147.
[I 2026-04-02 01:29:28,565] Trial 17 finished with value: 0.7746741154562384 and parameters: {'classifier': 'RandomForest', 'n_estimators': 181, 'max_depth': 12, 'min_samples_split': 3, 'min_samples_leaf': 10, 'bootstrap': False}. Best is trial 17 with value: 0.7746741154562384.
[I 2026-04-02 01:29:28,605] Trial 18 finished with value: 0.7635009310986964 and parameters: {'classifier': 'SVM', 'C': 0.2085671120628525, 'kernel': 'rbf', 'gamma': 'scale'}. Best is trial 17 with value: 0.7746741154562384.
[I 2026-04-02 01:29:30,712] Trial 19 finished with value: 0.7672253258845437 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 144, 'learning_rate': 0.011941578873033327, 'max_depth': 11, 'min_samples_split': 4, 'min_samples_leaf': 7}. Best is trial 17 with value: 0.7746741154562384.
[I 2026-04-02 01:29:31,548] Trial 20 finished with value: 0.7746741154562384 and parameters: {'classifier': 'RandomForest', 'n_estimators': 174, 'max_depth': 10, 'min_samples_split': 2, 'min_samples_leaf': 10, 'bootstrap': False}. Best is trial 17 with value: 0.7746741154562384.
[I 2026-04-02 01:29:32,369] Trial 21 finished with value: 0.7783985102420856 and parameters: {'classifier': 'RandomForest', 'n_estimators': 170, 'max_depth': 11, 'min_samples_split': 2, 'min_samples_leaf': 10, 'bootstrap': False}. Best is trial 21 with value: 0.7783985102420856.
[I 2026-04-02 01:29:33,184] Trial 22 finished with value: 0.7765363128491621 and parameters: {'classifier': 'RandomForest', 'n_estimators': 172, 'max_depth': 11, 'min_samples_split': 2, 'min_samples_leaf': 10, 'bootstrap': False}. Best is trial 21 with value: 0.7783985102420856.
[I 2026-04-02 01:29:33,765] Trial 23 finished with value: 0.7839851024208566 and parameters: {'classifier': 'RandomForest', 'n_estimators': 116, 'max_depth': 13, 'min_samples_split': 3, 'min_samples_leaf': 9, 'bootstrap': False}. Best is trial 23 with value: 0.7839851024208566.
[I 2026-04-02 01:29:34,334] Trial 24 finished with value: 0.7802607076350093 and parameters: {'classifier': 'RandomForest', 'n_estimators': 111, 'max_depth': 9, 'min_samples_split': 3, 'min_samples_leaf': 9, 'bootstrap': False}. Best is trial 23 with value: 0.7839851024208566.
[I 2026-04-02 01:29:34,843] Trial 25 finished with value: 0.7709497206703911 and parameters: {'classifier': 'RandomForest', 'n_estimators': 104, 'max_depth': 9, 'min_samples_split': 3, 'min_samples_leaf': 8, 'bootstrap': False}. Best is trial 23 with value: 0.7839851024208566.
[I 2026-04-02 01:29:35,412] Trial 26 finished with value: 0.7839851024208566 and parameters: {'classifier': 'RandomForest', 'n_estimators': 112, 'max_depth': 14, 'min_samples_split': 4, 'min_samples_leaf': 9, 'bootstrap': False}. Best is trial 23 with value: 0.7839851024208566.
[I 2026-04-02 01:29:36,324] Trial 27 finished with value: 0.7783985102420857 and parameters: {'classifier': 'RandomForest', 'n_estimators': 114, 'max_depth': 14, 'min_samples_split': 4, 'min_samples_leaf': 8, 'bootstrap': False}. Best is trial 23 with value: 0.7839851024208566.
[I 2026-04-02 01:29:37,603] Trial 28 finished with value: 0.7579143389199254 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 76, 'learning_rate': 0.012609653819009178, 'max_depth': 6, 'min_samples_split': 4, 'min_samples_leaf': 9}. Best is trial 23 with value: 0.7839851024208566.
[I 2026-04-02 01:29:37,650] Trial 29 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.10447725712254269, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 29 with value: 0.7877094972067038.
[I 2026-04-02 01:29:37,698] Trial 30 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.1059767384327693, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 29 with value: 0.7877094972067038.
[I 2026-04-02 01:29:37,747] Trial 31 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.136927773284804, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 31 with value: 0.7895716945996275.
[I 2026-04-02 01:29:37,799] Trial 32 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.11691462665841215, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 31 with value: 0.7895716945996275.
[I 2026-04-02 01:29:37,854] Trial 33 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.10044326265699109, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 31 with value: 0.7895716945996275.
[I 2026-04-02 01:29:37,913] Trial 34 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.10043137513626986, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 31 with value: 0.7895716945996275.
[I 2026-04-02 01:29:37,968] Trial 35 finished with value: 0.7839851024208566 and parameters: {'classifier': 'SVM', 'C': 0.42441446767376306, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 31 with value: 0.7895716945996275.
[I 2026-04-02 01:29:38,027] Trial 36 finished with value: 0.7839851024208566 and parameters: {'classifier': 'SVM', 'C': 0.5411949890772134, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 31 with value: 0.7895716945996275.
[I 2026-04-02 01:29:38,083] Trial 37 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.29253187658112384, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 31 with value: 0.7895716945996275.
[I 2026-04-02 01:29:38,136] Trial 38 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.1170737316905571, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 31 with value: 0.7895716945996275.
[I 2026-04-02 01:29:38,202] Trial 39 finished with value: 0.7839851024208566 and parameters: {'classifier': 'SVM', 'C': 1.0325009420795341, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 31 with value: 0.7895716945996275.
[I 2026-04-02 01:29:38,255] Trial 40 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.22698113334288691, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 31 with value: 0.7895716945996275.
[I 2026-04-02 01:29:38,310] Trial 41 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.10377849243262181, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 31 with value: 0.7895716945996275.
[I 2026-04-02 01:29:38,345] Trial 42 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.11105939008873128, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 31 with value: 0.7895716945996275.
[I 2026-04-02 01:29:38,377] Trial 43 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.2049594814293005, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 31 with value: 0.7895716945996275.
[I 2026-04-02 01:29:38,409] Trial 44 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.18872955567649777, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 31 with value: 0.7895716945996275.
[I 2026-04-02 01:29:38,450] Trial 45 finished with value: 0.7672253258845437 and parameters: {'classifier': 'SVM', 'C': 0.7902790744580211, 'kernel': 'rbf', 'gamma': 'scale'}. Best is trial 31 with value: 0.7895716945996275.
[I 2026-04-02 01:29:38,486] Trial 46 finished with value: 0.7150837988826816 and parameters: {'classifier': 'SVM', 'C': 0.2007848506014746, 'kernel': 'poly', 'gamma': 'auto'}. Best is trial 31 with value: 0.7895716945996275.
[I 2026-04-02 01:29:38,527] Trial 47 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.10090647609094679, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 31 with value: 0.7895716945996275.
[I 2026-04-02 01:29:38,567] Trial 48 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.330952101665093, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 31 with value: 0.7895716945996275.
[I 2026-04-02 01:29:38,607] Trial 49 finished with value: 0.7839851024208566 and parameters: {'classifier': 'SVM', 'C': 1.595424071887815, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 31 with value: 0.7895716945996275.
[I 2026-04-02 01:29:38,640] Trial 50 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.16692683710221234, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 31 with value: 0.7895716945996275.
[I 2026-04-02 01:29:38,675] Trial 51 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.1441747850066188, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 31 with value: 0.7895716945996275.
[I 2026-04-02 01:29:38,709] Trial 52 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.14213551344869207, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 31 with value: 0.7895716945996275.
[I 2026-04-02 01:29:38,787] Trial 53 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 11.286576249748617, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 31 with value: 0.7895716945996275.
[I 2026-04-02 01:29:44,337] Trial 54 finished with value: 0.7374301675977653 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 267, 'learning_rate': 0.034796627442578235, 'max_depth': 18, 'min_samples_split': 9, 'min_samples_leaf': 4}. Best is trial 31 with value: 0.7895716945996275.
[I 2026-04-02 01:29:44,369] Trial 55 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.1744525248999785, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 31 with value: 0.7895716945996275.
[I 2026-04-02 01:29:44,408] Trial 56 finished with value: 0.7653631284916201 and parameters: {'classifier': 'SVM', 'C': 0.3209961804968217, 'kernel': 'rbf', 'gamma': 'scale'}. Best is trial 31 with value: 0.7895716945996275.
[I 2026-04-02 01:29:44,456] Trial 57 finished with value: 0.7728119180633147 and parameters: {'classifier': 'SVM', 'C': 0.15008182569898518, 'kernel': 'sigmoid', 'gamma': 'auto'}. Best is trial 31 with value: 0.7895716945996275.
[I 2026-04-02 01:29:44,495] Trial 58 finished with value: 0.7411545623836128 and parameters: {'classifier': 'SVM', 'C': 0.5183246972617829, 'kernel': 'poly', 'gamma': 'scale'}. Best is trial 31 with value: 0.7895716945996275.
[I 2026-04-02 01:29:45,764] Trial 59 finished with value: 0.7802607076350093 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 207, 'learning_rate': 0.06054217687645819, 'max_depth': 3, 'min_samples_split': 6, 'min_samples_leaf': 6}. Best is trial 31 with value: 0.7895716945996275.
[I 2026-04-02 01:29:45,817] Trial 60 finished with value: 0.6927374301675977 and parameters: {'classifier': 'SVM', 'C': 14.912123410070041, 'kernel': 'sigmoid', 'gamma': 'scale'}. Best is trial 31 with value: 0.7895716945996275.
[I 2026-04-02 01:29:45,850] Trial 61 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.14705158927774004, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 31 with value: 0.7895716945996275.
[I 2026-04-02 01:29:45,883] Trial 62 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.14278159025215703, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 31 with value: 0.7895716945996275.
[I 2026-04-02 01:29:45,915] Trial 63 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.2828957635113871, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 31 with value: 0.7895716945996275.
[I 2026-04-02 01:29:45,946] Trial 64 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.15894936647291052, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 31 with value: 0.7895716945996275.
[I 2026-04-02 01:29:45,978] Trial 65 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.15163447980814992, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 31 with value: 0.7895716945996275.
[I 2026-04-02 01:29:46,020] Trial 66 finished with value: 0.7132216014897579 and parameters: {'classifier': 'SVM', 'C': 4.70208660220825, 'kernel': 'sigmoid', 'gamma': 'scale'}. Best is trial 31 with value: 0.7895716945996275.
[I 2026-04-02 01:29:46,209] Trial 67 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 36.47922680811159, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 31 with value: 0.7895716945996275.
[I 2026-04-02 01:29:46,813] Trial 68 finished with value: 0.7486033519553073 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 57, 'learning_rate': 0.02964581147107078, 'max_depth': 5, 'min_samples_split': 9, 'min_samples_leaf': 3}. Best is trial 31 with value: 0.7895716945996275.
[I 2026-04-02 01:29:46,863] Trial 69 finished with value: 0.7113594040968342 and parameters: {'classifier': 'SVM', 'C': 0.13643831502534584, 'kernel': 'poly', 'gamma': 'auto'}. Best is trial 31 with value: 0.7895716945996275.
[I 2026-04-02 01:29:46,897] Trial 70 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.2574198630699008, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 31 with value: 0.7895716945996275.
[I 2026-04-02 01:29:46,928] Trial 71 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.13890691039436973, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 31 with value: 0.7895716945996275.
[I 2026-04-02 01:29:46,960] Trial 72 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.12868161750165052, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 31 with value: 0.7895716945996275.
[I 2026-04-02 01:29:46,993] Trial 73 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.12847938959080588, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 31 with value: 0.7895716945996275.
[I 2026-04-02 01:29:47,030] Trial 74 finished with value: 0.7821229050279329 and parameters: {'classifier': 'SVM', 'C': 0.3893006332971444, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 31 with value: 0.7895716945996275.
[I 2026-04-02 01:29:47,071] Trial 75 finished with value: 0.7541899441340782 and parameters: {'classifier': 'SVM', 'C': 0.2296189224630759, 'kernel': 'rbf', 'gamma': 'scale'}. Best is trial 31 with value: 0.7895716945996275.
[I 2026-04-02 01:29:47,108] Trial 76 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.10152890358782043, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 31 with value: 0.7895716945996275.
[I 2026-04-02 01:29:47,140] Trial 77 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.21385463047375056, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 31 with value: 0.7895716945996275.
[I 2026-04-02 01:29:47,173] Trial 78 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.130740020269073, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 31 with value: 0.7895716945996275.
[I 2026-04-02 01:29:47,207] Trial 79 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.26703765083610753, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 31 with value: 0.7895716945996275.

In [25]:
# Retrieve the best trial
best_trial = study.best_trial
print("Best trial parameters:", best_trial.params)
print("Best trial accuracy:", best_trial.value)

Best trial parameters: {'classifier': 'SVM', 'C': 0.136927773284804, 'kernel': 'linear', 'gamma': 'scale'}
Best trial accuracy: 0.7895716945996275

In [26]:
study.trials_dataframe()

,number,value,datetime_start,datetime_complete,duration,params_C,params_bootstrap,params_classifier,params_gamma,params_kernel,params_learning_rate,params_max_depth,params_min_samples_leaf,params_min_samples_split,params_n_estimators,state
0,0,0.746741,2026-04-02 01:29:07.386648,2026-04-02 01:29:08.243146,0 days 00:00:00.856498,NaN,False,RandomForest,NaN,NaN,NaN,3.0,5.0,3.0,200.0,COMPLETE
1,1,0.683426,2026-04-02 01:29:08.244185,2026-04-02 01:29:08.277890,0 days 00:00:00.033705,21.295852,NaN,SVM,scale,sigmoid,NaN,NaN,NaN,NaN,NaN,COMPLETE
2,2,0.731844,2026-04-02 01:29:08.279003,2026-04-02 01:29:09.111300,0 days 00:00:00.832297,NaN,NaN,GradientBoosting,NaN,NaN,0.197109,3.0,1.0,10.0,131.0,COMPLETE
3,3,0.759777,2026-04-02 01:29:09.112489,2026-04-02 01:29:09.590912,0 days 00:00:00.478423,NaN,True,RandomForest,NaN,NaN,NaN,8.0,9.0,10.0,84.0,COMPLETE
4,4,0.716946,2026-04-02 01:29:09.592247,2026-04-02 01:29:09.627086,0 days 00:00:00.034839,2.952072,NaN,SVM,auto,sigmoid,NaN,NaN,NaN,NaN,NaN,COMPLETE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,95,0.787709,2026-04-02 01:29:53.263280,2026-04-02 01:29:53.298703,0 days 00:00:00.035423,0.175802,NaN,SVM,scale,linear,NaN,NaN,NaN,NaN,NaN,COMPLETE
96,96,0.789572,2026-04-02 01:29:53.299838,2026-04-02 01:29:53.332400,0 days 00:00:00.032562,0.120935,NaN,SVM,scale,linear,NaN,NaN,NaN,NaN,NaN,COMPLETE
97,97,0.754190,2026-04-02 01:29:53.333303,2026-04-02 01:29:53.379385,0 days 00:00:00.046082,0.329352,NaN,SVM,scale,sigmoid,NaN,NaN,NaN,NaN,NaN,COMPLETE
98,98,0.785847,2026-04-02 01:29:53.380497,2026-04-02 01:29:53.421530,0 days 00:00:00.041033,1.937069,NaN,SVM,scale,linear,NaN,NaN,NaN,NaN,NaN,COMPLETE
99,99,0.787709,2026-04-02 01:29:53.422530,2026-04-02 01:29:53.454786,0 days 00:00:00.032256,0.156563,NaN,SVM,scale,linear,NaN,NaN,NaN,NaN,NaN,COMPLETE

In [27]:
study.trials_dataframe()['params_classifier'].value_counts()

params_classifier
SVM                 71
RandomForest        20
GradientBoosting     9
Name: count, dtype: int64

In [28]:
study.trials_dataframe().groupby('params_classifier')['value'].mean()

params_classifier
GradientBoosting    0.751293
RandomForest        0.771508
SVM                 0.775146
Name: value, dtype: float64

In [29]:
# 1. Optimization History
plot_optimization_history(study).show()

In [30]:
# 3. Slice Plot
plot_slice(study).show()

In [31]:
# 5. Hyperparameter Importance
plot_param_importances(study).show()

In [32]:
import optuna
import xgboost as xgb
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_iris
from sklearn.metrics import accuracy_score
import numpy as np

# Load the Iris dataset
X, y = load_iris(return_X_y=True)

# Split the dataset into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Define the objective function for XGBoost
def objective(trial):
    # Hyperparameter search space
    param = {
        'verbosity': 0,
        'objective': 'multi:softprob',
        'num_class': 3,
        'eval_metric': 'mlogloss',  # Ensure that the eval_metric is specified here
        'booster': 'gbtree',
        'lambda': trial.suggest_float('lambda', 1e-8, 1.0, log=True),
        'alpha': trial.suggest_float('alpha', 1e-8, 1.0, log=True),
        'eta': trial.suggest_float('eta', 0.01, 0.3),
        'gamma': trial.suggest_float('gamma', 1e-8, 1.0, log=True),
        'max_depth': trial.suggest_int('max_depth', 3, 9),
        'min_child_weight': trial.suggest_int('min_child_weight', 1, 10),
        'subsample': trial.suggest_float('subsample', 0.4, 1.0),
        'colsample_bytree': trial.suggest_float('colsample_bytree', 0.4, 1.0),
        'n_estimators': 300,
    }

    # Create DMatrix for XGBoost
    dtrain = xgb.DMatrix(X_train, label=y_train)
    dtest = xgb.DMatrix(X_test, label=y_test)

    # Define a pruning callback based on evaluation metrics
    pruning_callback = optuna.integration.XGBoostPruningCallback(trial, "eval-mlogloss")  # Match the metric name in the evals list

    # Train the model
    bst = xgb.train(
        param,
        dtrain,
        num_boost_round=300,
        evals=[(dtrain, "train"), (dtest, "eval")],  # Ensure the eval datasets and names are specified
        early_stopping_rounds=30,
        callbacks=[pruning_callback]
    )

    # Predict on the test set
    preds = bst.predict(dtest)
    best_preds = [int(np.argmax(line)) for line in preds]

    # Return accuracy as the objective value
    accuracy = accuracy_score(y_test, best_preds)
    return accuracy

# Create a study with pruning
study = optuna.create_study(direction='maximize', pruner=optuna.pruners.SuccessiveHalvingPruner())
study.optimize(objective, n_trials=50)

# Output the best trial
print(f"Best trial: {study.best_trial.params}")
print(f"Best accuracy: {study.best_value}")

[I 2026-04-02 01:29:54,311] A new study created in memory with name: no-name-c6d17d74-0268-4ef5-8af4-ee0ec2900a1c
[W 2026-04-02 01:29:54,350] Trial 0 failed with parameters: {'lambda': 0.9236885695035536, 'alpha': 5.087484923411386e-06, 'eta': 0.16765780670172434, 'gamma': 7.962081029724645e-07, 'max_depth': 6, 'min_child_weight': 5, 'subsample': 0.934899133276875, 'colsample_bytree': 0.9548926980809073} because of the following error: ModuleNotFoundError('\nCould not find `optuna-integration` for `xgboost`.\nPlease run `pip install optuna-integration[xgboost]`.').
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/optuna/integration/xgboost.py", line 5, in <module>
    from optuna_integration.xgboost import XGBoostPruningCallback
ModuleNotFoundError: No module named 'optuna_integration'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/optuna/integration/__init__.py", line 132, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/usr/local/lib/python3.12/dist-packages/optuna/integration/xgboost.py", line 7, in <module>
    raise ModuleNotFoundError(_INTEGRATION_IMPORT_ERROR_TEMPLATE.format("xgboost"))
ModuleNotFoundError:
Could not find `optuna-integration` for `xgboost`.
Please run `pip install optuna-integration[xgboost]`.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/optuna/study/_optimize.py", line 206, in _run_trial
    value_or_values = func(trial)
                      ^^^^^^^^^^^
  File "/tmp/ipykernel_5683/3918831170.py", line 39, in objective
    pruning_callback = optuna.integration.XGBoostPruningCallback(trial, "eval-mlogloss")  # Match the metric name in the evals list
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/optuna/integration/__init__.py", line 120, in __getattr__
    module = self._get_module(self._class_to_module[name])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/optuna/integration/__init__.py", line 134, in _get_module
    raise ModuleNotFoundError(_INTEGRATION_IMPORT_ERROR_TEMPLATE.format(module_name))
ModuleNotFoundError:
Could not find `optuna-integration` for `xgboost`.
Please run `pip install optuna-integration[xgboost]`.
[W 2026-04-02 01:29:54,353] Trial 0 failed with value None.

ModuleNotFoundError:
Could not find `optuna-integration` for `xgboost`.
Please run `pip install optuna-integration[xgboost]`.

In [ ]:
! pip install optuna-integration[xgboost]

In [ ]:
from optuna.visualization import plot_intermediate_values

# 1. Plot intermediate values during the trials
plot_intermediate_values(study).show()