Coding a simple training pipline using a dataset.

$Vraj$ $Patel$

In [35]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [36]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [37]:
df.shape

(569, 33)

In [38]:
df.drop(columns=['id','Unnamed: 32'], inplace=True)

In [39]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [40]:
X = df.iloc[:,1:]
y = df.iloc[:,0]

In [41]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2)

In [42]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [43]:
X_train

array([[-1.31613439,  2.0156279 , -1.32649697, ..., -1.74717138,
        -0.66696159, -0.80654492],
       [ 0.47925539,  0.85769221,  0.57206963, ...,  1.36770423,
         0.63639126,  2.37905836],
       [-0.37085051,  0.75517879, -0.40828409, ..., -0.31821837,
        -0.08950613, -0.17642559],
       ...,
       [-0.34260779, -0.70330761, -0.38130188, ..., -0.86201991,
         1.1746972 , -0.75317416],
       [ 0.0330204 ,  0.3031878 ,  0.02874598, ...,  0.30337849,
        -0.57071901, -0.29636634],
       [ 0.04714176,  0.68062357,  0.19268337, ...,  0.98638465,
        -0.06503768,  1.69040335]])

In [44]:
y_train

557    B
118    M
135    M
347    B
273    B
      ..
529    B
111    B
268    B
476    B
62     M
Name: diagnosis, Length: 455, dtype: object

In [45]:
X_test

array([[-0.17597574, -0.11152559, -0.17443825, ...,  0.43814204,
         1.03441141,  0.16675415],
       [-1.19638525, -0.82678969, -1.17359776, ..., -0.74747089,
        -0.62291838,  0.47894442],
       [-0.6052651 , -0.23034796, -0.65398576, ..., -0.78299946,
        -0.16128026, -0.55461197],
       ...,
       [ 2.05802349, -0.96192102,  2.02747382, ...,  1.26356876,
        -0.25099791,  0.16732803],
       [ 1.84055454,  2.35345622,  1.97841526, ...,  2.31104905,
         1.96258134,  2.31019286],
       [-0.37085051,  2.37675473, -0.42341049, ..., -0.7520651 ,
        -0.77788524, -1.08487632]])

In [46]:
y_test

526    B
524    B
52     B
515    B
9      M
      ..
519    B
205    M
372    M
567    M
552    B
Name: diagnosis, Length: 114, dtype: object

In [47]:
from sklearn.preprocessing import LabelEncoder

# Merge train and test labels, encode them, then split back
all_y = list(y_train) + list(y_test)

encoder = LabelEncoder()
all_encoded = encoder.fit_transform(all_y)

y_train = all_encoded[:len(y_train)]
y_test  = all_encoded[len(y_train):]

In [48]:
y_train

array([0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1,
       1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0,
       1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0,
       1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1])

In [49]:
y_test

array([0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1,
       1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 0])

# now coverting the numpy arrays to pytorch tensors

In [73]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_train)

In [74]:
y_train_tensor

tensor([0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
        1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0,
        1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1,
        0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1,
        1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0,
        1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0,
        0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1,
        0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0,
        0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0,
        0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0,
        0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0,
        1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0,
        1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0,
        0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1,
        0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
        0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
        1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0,
        0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1,
        1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1])

In [75]:
X_train_tensor

tensor([[-1.3161,  2.0156, -1.3265,  ..., -1.7472, -0.6670, -0.8065],
        [ 0.4793,  0.8577,  0.5721,  ...,  1.3677,  0.6364,  2.3791],
        [-0.3709,  0.7552, -0.4083,  ..., -0.3182, -0.0895, -0.1764],
        ...,
        [-0.3426, -0.7033, -0.3813,  ..., -0.8620,  1.1747, -0.7532],
        [ 0.0330,  0.3032,  0.0287,  ...,  0.3034, -0.5707, -0.2964],
        [ 0.0471,  0.6806,  0.1927,  ...,  0.9864, -0.0650,  1.6904]],
       dtype=torch.float64)

In [76]:
X_train_tensor.shape

torch.Size([455, 30])

# Defining the model.

In [77]:
class MySimpleNN():

  def __init__(self, X):

    self.weights = torch.rand(X.shape[1],1, dtype=torch.float64, requires_grad=True)
    self.bias = torch.zeros(1, dtype=torch.float64, requires_grad=True)

  def forward(self, X):
    z = torch.matmul(X,self.weights) + self.bias
    y_pred = torch.sigmoid(z)
    return y_pred

  def loss_function(self, y_pred, y):
    # clamp predictiosn to avoid log(0)
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1-epsilon)

    # calculate loss
    loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1-y_pred)).mean()
    return loss

# Defining the important parameters

In [78]:
lr = 0.1 # learning rate
epochs = 50

# training pipeline

In [79]:
# creating the model

model = MySimpleNN(X_train_tensor)

# loop epochs times
for epoch in range(epochs):

# forward pass
  y_pred = model.forward(X_train_tensor)

# loss calculate
  loss = model.loss_function(y_pred, y_train_tensor)

# backward pass
  loss.backward()

# parameters update
  with torch.no_grad():
    model.weights -= lr*model.weights.grad
    model.bias -= lr*model.bias.grad

# zero gradients
  model.weights.grad.zero_()
  model.bias.grad.zero_()

# printing the loss in each epoch
  print(f'Epoch: {epoch + 1 }, Loss: {loss.item()}')

Epoch: 1, Loss: 3.4928400081662017
Epoch: 2, Loss: 3.3640183428662294
Epoch: 3, Loss: 3.2333456805239265
Epoch: 4, Loss: 3.0984027899953133
Epoch: 5, Loss: 2.9600447722970307
Epoch: 6, Loss: 2.8173301392601164
Epoch: 7, Loss: 2.668247671915624
Epoch: 8, Loss: 2.5153669011028326
Epoch: 9, Loss: 2.3639811069455217
Epoch: 10, Loss: 2.2087561509673144
Epoch: 11, Loss: 2.0515368154681193
Epoch: 12, Loss: 1.8991508297398711
Epoch: 13, Loss: 1.7483821484946769
Epoch: 14, Loss: 1.598250539753273
Epoch: 15, Loss: 1.4559344161180496
Epoch: 16, Loss: 1.3264175938400715
Epoch: 17, Loss: 1.2115565562255666
Epoch: 18, Loss: 1.1123395207997018
Epoch: 19, Loss: 1.0279738187728154
Epoch: 20, Loss: 0.9603880898995161
Epoch: 21, Loss: 0.9077457166501096
Epoch: 22, Loss: 0.8673840649634443
Epoch: 23, Loss: 0.8365521684366976
Epoch: 24, Loss: 0.8128646070500646
Epoch: 25, Loss: 0.7944371016198398
Epoch: 26, Loss: 0.779858173872132
Epoch: 27, Loss: 0.7681054482490066
Epoch: 28, Loss: 0.7584540278967703
Epoch: 29, Loss: 0.7503947030410838
Epoch: 30, Loss: 0.7435683556560917
Epoch: 31, Loss: 0.7377175846163458
Epoch: 32, Loss: 0.732653330925477
Epoch: 33, Loss: 0.7282328808500912
Epoch: 34, Loss: 0.7243457020289454
Epoch: 35, Loss: 0.7209043389774656
Epoch: 36, Loss: 0.717838457453583
Epoch: 37, Loss: 0.7150908203114807
Epoch: 38, Loss: 0.7126144554145568
Epoch: 39, Loss: 0.7103705781766524
Epoch: 40, Loss: 0.7083270119013783
Epoch: 41, Loss: 0.7064569533314932
Epoch: 42, Loss: 0.7047379897920489
Epoch: 43, Loss: 0.7031513075308692
Epoch: 44, Loss: 0.7016810498553595
Epoch: 45, Loss: 0.700313794946364
Epoch: 46, Loss: 0.6990381303477557
Epoch: 47, Loss: 0.6978443059662319
Epoch: 48, Loss: 0.6967239509460083
Epoch: 49, Loss: 0.6956698425099572
Epoch: 50, Loss: 0.6946757170433976

In [80]:
model.weights

tensor([[-0.2137],
        [-0.0459],
        [ 0.0340],
        [ 0.4162],
        [ 0.1139],
        [-0.4278],
        [-0.0233],
        [-0.5302],
        [ 0.2314],
        [ 0.4347],
        [ 0.2388],
        [-0.1002],
        [-0.4401],
        [ 0.2703],
        [-0.1354],
        [ 0.1202],
        [ 0.3391],
        [ 0.3081],
        [-0.0840],
        [-0.2214],
        [ 0.1379],
        [ 0.2639],
        [-0.2688],
        [ 0.2923],
        [-0.1895],
        [-0.2487],
        [-0.1151],
        [ 0.1650],
        [ 0.1815],
        [-0.0074]], dtype=torch.float64, requires_grad=True)

In [81]:
model.bias

tensor([-0.3231], dtype=torch.float64, requires_grad=True)

# Evaluation

In [88]:
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.5).float()
  accuracy = (y_pred == y).mean()

print(accuracy)

0.0