#Question and Answering system using RNN in pytorch

## Steps:

1. Loading the dataset
2. Tokenization
3. Vocabulary
4. Convert words to numerical

In [1]:
import pandas as pd
df = pd.read_csv("100_Unique_QA_Dataset.csv")

In [2]:
df.head()

                                          question      answer
0                   What is the capital of France?       Paris
1                  What is the capital of Germany?      Berlin
2               Who wrote 'To Kill a Mockingbird'?  Harper-Lee
3  What is the largest planet in our solar system?     Jupiter
4   What is the boiling point of water in Celsius?         100

In [3]:
# tokenize
def tokenize(text):
  text = text.lower()
  text = text.replace('?','')
  text = text.replace("'",'')
  return text.split()

In [4]:
# creating a vocab

vocab = {'<UNK>':0}

In [11]:
def make_vocab(row):
  tokenized_question = tokenize(row['question'])
  tokenized_answer = tokenize(row['answer'])
  merged_tokens = tokenized_question + tokenized_answer

  for token in merged_tokens:

    if token not in vocab:
      vocab[token] = len(vocab) # this is the length of the dict that we are building. it's dynamic.

In [12]:
df.apply(make_vocab, axis=1)

0     None
1     None
2     None
3     None
4     None
      ...
85    None
86    None
87    None
88    None
89    None
Length: 90, dtype: object

In [13]:
vocab

{'<UNK>': 0,
 'what': 1,
 'is': 2,
 'the': 3,
 'capital': 4,
 'of': 5,
 'france': 6,
 'paris': 7,
 'germany': 8,
 'berlin': 9,
 'who': 10,
 'wrote': 11,
 'to': 12,
 'kill': 13,
 'a': 14,
 'mockingbird': 15,
 'harper-lee': 16,
 'largest': 17,
 'planet': 18,
 'in': 19,
 'our': 20,
 'solar': 21,
 'system': 22,
 'jupiter': 23,
 'boiling': 24,
 'point': 25,
 'water': 26,
 'celsius': 27,
 '100': 28,
 'painted': 29,
 'mona': 30,
 'lisa': 31,
 'leonardo-da-vinci': 32,
 'square': 33,
 'root': 34,
 '64': 35,
 '8': 36,
 'chemical': 37,
 'symbol': 38,
 'for': 39,
 'gold': 40,
 'au': 41,
 'which': 42,
 'year': 43,
 'did': 44,
 'world': 45,
 'war': 46,
 'ii': 47,
 'end': 48,
 '1945': 49,
 'longest': 50,
 'river': 51,
 'nile': 52,
 'japan': 53,
 'tokyo': 54,
 'developed': 55,
 'theory': 56,
 'relativity': 57,
 'albert-einstein': 58,
 'freezing': 59,
 'fahrenheit': 60,
 '32': 61,
 'known': 62,
 'as': 63,
 'red': 64,
 'mars': 65,
 'author': 66,
 '1984': 67,
 'george-orwell': 68,
 'currency': 69,
 'united': 70,
 'kingdom': 71,
 'pound': 72,
 'india': 73,
 'delhi': 74,
 'discovered': 75,
 'gravity': 76,
 'newton': 77,
 'how': 78,
 'many': 79,
 'continents': 80,
 'are': 81,
 'there': 82,
 'on': 83,
 'earth': 84,
 '7': 85,
 'gas': 86,
 'do': 87,
 'plants': 88,
 'use': 89,
 'photosynthesis': 90,
 'co2': 91,
 'smallest': 92,
 'prime': 93,
 'number': 94,
 '2': 95,
 'invented': 96,
 'telephone': 97,
 'alexander-graham-bell': 98,
 'australia': 99,
 'canberra': 100,
 'ocean': 101,
 'pacific-ocean': 102,
 'speed': 103,
 'light': 104,
 'vacuum': 105,
 '299,792,458m/s': 106,
 'language': 107,
 'spoken': 108,
 'brazil': 109,
 'portuguese': 110,
 'penicillin': 111,
 'alexander-fleming': 112,
 'canada': 113,
 'ottawa': 114,
 'mammal': 115,
 'whale': 116,
 'element': 117,
 'has': 118,
 'atomic': 119,
 '1': 120,
 'hydrogen': 121,
 'tallest': 122,
 'mountain': 123,
 'everest': 124,
 'city': 125,
 'big': 126,
 'apple': 127,
 'newyork': 128,
 'planets': 129,
 'starry': 130,
 'night': 131,
 'vangogh': 132,
 'formula': 133,
 'h2o': 134,
 'italy': 135,
 'rome': 136,
 'country': 137,
 'famous': 138,
 'sushi': 139,
 'was': 140,
 'first': 141,
 'person': 142,
 'step': 143,
 'moon': 144,
 'armstrong': 145,
 'main': 146,
 'ingredient': 147,
 'guacamole': 148,
 'avocado': 149,
 'sides': 150,
 'does': 151,
 'hexagon': 152,
 'have': 153,
 '6': 154,
 'china': 155,
 'yuan': 156,
 'pride': 157,
 'and': 158,
 'prejudice': 159,
 'jane-austen': 160,
 'iron': 161,
 'fe': 162,
 'hardest': 163,
 'natural': 164,
 'substance': 165,
 'diamond': 166,
 'continent': 167,
 'by': 168,
 'area': 169,
 'asia': 170,
 'president': 171,
 'states': 172,
 'george-washington': 173,
 'bird': 174,
 'its': 175,
 'ability': 176,
 'mimic': 177,
 'sounds': 178,
 'parrot': 179,
 'longest-running': 180,
 'animated': 181,
 'tv': 182,
 'show': 183,
 'simpsons': 184,
 'vaticancity': 185,
 'most': 186,
 'moons': 187,
 'saturn': 188,
 'romeo': 189,
 'juliet': 190,
 'shakespeare': 191,
 'earths': 192,
 'atmosphere': 193,
 'nitrogen': 194,
 'bones': 195,
 'adult': 196,
 'human': 197,
 'body': 198,
 '206': 199,
 'metal': 200,
 'liquid': 201,
 'at': 202,
 'room': 203,
 'temperature': 204,
 'mercury': 205,
 'russia': 206,
 'moscow': 207,
 'electricity': 208,
 'benjamin-franklin': 209,
 'second-largest': 210,
 'land': 211,
 'color': 212,
 'ripe': 213,
 'banana': 214,
 'yellow': 215,
 'month': 216,
 '28': 217,
 'days': 218,
 'common': 219,
 'february': 220,
 'study': 221,
 'living': 222,
 'organisms': 223,
 'called': 224,
 'biology': 225,
 'home': 226,
 'great': 227,
 'wall': 228,
 'bees': 229,
 'collect': 230,
 'from': 231,
 'flowers': 232,
 'nectar': 233,
 'opposite': 234,
 'day': 235,
 'south': 236,
 'korea': 237,
 'seoul': 238,
 'bulb': 239,
 'edison': 240,
 'humans': 241,
 'breathe': 242,
 'survival': 243,
 'oxygen': 244,
 '144': 245,
 '12': 246,
 'pyramids': 247,
 'giza': 248,
 'egypt': 249,
 'sea': 250,
 'creature': 251,
 'eight': 252,
 'arms': 253,
 'octopus': 254,
 'holiday': 255,
 'celebrated': 256,
 'december': 257,
 '25': 258,
 'christmas': 259,
 'yen': 260,
 'legs': 261,
 'spider': 262,
 'sport': 263,
 'uses': 264,
 'net,': 265,
 'ball,': 266,
 'hoop': 267,
 'basketball': 268,
 'kangaroos': 269,
 'female': 270,
 'minister': 271,
 'uk': 272,
 'margaretthatcher': 273,
 'fastest': 274,
 'animal': 275,
 'cheetah': 276,
 'periodic': 277,
 'table': 278,
 'spain': 279,
 'madrid': 280,
 'closest': 281,
 'sun': 282,
 'father': 283,
 'computers': 284,
 'charlesbabbage': 285,
 'mexico': 286,
 'mexicocity': 287,
 'colors': 288,
 'rainbow': 289,
 'musical': 290,
 'instrument': 291,
 'black': 292,
 'white': 293,
 'keys': 294,
 'piano': 295,
 'americas': 296,
 '1492': 297,
 'christophercolumbus': 298,
 'disney': 299,
 'character': 300,
 'long': 301,
 'nose': 302,
 'grows': 303,
 'it': 304,
 'when': 305,
 'lying': 306,
 'pinocchio': 307,
 'directed': 308,
 'movie': 309,
 'titanic': 310,
 'jamescameron': 311,
 'superhero': 312,
 'also': 313,
 'dark': 314,
 'knight': 315,
 'batman': 316,
 'brasilia': 317,
 'fruit': 318,
 'king': 319,
 'fruits': 320,
 'mango': 321,
 'eiffel': 322,
 'tower': 323}

In [14]:
len(vocab)

324

In [15]:
# convert words to numerical indices

def text_to_indices(text, vocab):

  indexed_text = []

  for token in tokenize(text):

    if token in vocab:
      indexed_text.append(vocab[token])
    else:
      indexed_text.append(vocab['<UNK>'])

  return indexed_text

In [16]:
text_to_indices("Who is vraj patel", vocab)

[10, 2, 0, 0]

In [17]:
import torch
from torch.utils.data import Dataset, DataLoader

In [20]:
class QADataset(Dataset):

  def __init__(self, df, vocab):

    self.df = df
    self.vocab = vocab

  def __len__(self):
    return self.df.shape[0]

  def __getitem__(self, index):

    indexed_question = text_to_indices(self.df.iloc[index]['question'], self.vocab)
    indexed_answer = text_to_indices(self.df.iloc[index]['answer'], self.vocab)

    return torch.tensor(indexed_question), torch.tensor(indexed_answer)

In [21]:
dataset = QADataset(df, vocab)

In [22]:
dataset[32]

(tensor([ 78,  79, 129,  81,  19,   3,  21,  22]), tensor([36]))

In [24]:
dataloader = DataLoader(dataset, batch_size=1, shuffle=True) # sice data is small, we have 1 per batch so no need for padding in data either

In [25]:
for question, answer in dataloader:
  print(question, answer)

tensor([[ 78,  79, 129,  81,  19,   3,  21,  22]]) tensor([[36]])
tensor([[  1,   2,   3, 221,   5, 222, 223, 224]]) tensor([[225]])
tensor([[  1,   2,   3,   4,   5, 113]]) tensor([[114]])
tensor([[  1,   2,   3,  17, 115,  83,  84]]) tensor([[116]])
tensor([[ 42, 250, 251, 118, 252, 253]]) tensor([[254]])
tensor([[ 42, 137,   2, 138,  39, 175, 269]]) tensor([[99]])
tensor([[ 42, 318,   2,  62,  63,   3, 319,   5, 320]]) tensor([[321]])
tensor([[ 10, 140,   3, 141, 171,   5,   3,  70, 172]]) tensor([[173]])
tensor([[ 42, 290, 291, 118, 292, 158, 293, 294]]) tensor([[295]])
tensor([[ 42, 263, 264,  14, 265, 266, 158, 267]]) tensor([[268]])
tensor([[ 42,  18,   2,   3, 281,  12,   3, 282]]) tensor([[205]])
tensor([[  1,   2,   3,   4,   5, 109]]) tensor([[317]])
tensor([[ 1,  2,  3,  4,  5, 73]]) tensor([[74]])
tensor([[  1,   2,   3,   4,   5, 135]]) tensor([[136]])
tensor([[1, 2, 3, 4, 5, 8]]) tensor([[9]])
tensor([[  1,   2,   3,   4,   5, 206]]) tensor([[207]])
tensor([[  1,   2,   3,  37,  38,  39, 161]]) tensor([[162]])
tensor([[ 42,  18, 118,   3, 186, 187]]) tensor([[188]])
tensor([[ 42, 255,   2, 256,  83, 257, 258]]) tensor([[259]])
tensor([[42, 43, 44, 45, 46, 47, 48]]) tensor([[49]])
tensor([[10, 11, 12, 13, 14, 15]]) tensor([[16]])
tensor([[ 1,  2,  3, 24, 25,  5, 26, 19, 27]]) tensor([[28]])
tensor([[ 10,   2,  62,  63,   3, 283,   5, 284]]) tensor([[285]])
tensor([[ 1,  2,  3, 33, 34,  5, 35]]) tensor([[36]])
tensor([[ 42, 167,   2,   3,  17, 168, 169]]) tensor([[170]])
tensor([[ 42, 137,   2, 138,  39, 139]]) tensor([[53]])
tensor([[ 42, 137, 118,   3, 247,   5, 248]]) tensor([[249]])
tensor([[ 10,  11, 157, 158, 159]]) tensor([[160]])
tensor([[ 42, 125,   2,  62,  63,   3, 126, 127]]) tensor([[128]])
tensor([[ 78,  79, 195,  81,  19,   3, 196, 197, 198]]) tensor([[199]])
tensor([[ 1,  2,  3, 50, 51, 19,  3, 45]]) tensor([[52]])
tensor([[ 78,  79, 150, 151,  14, 152, 153]]) tensor([[154]])
tensor([[ 42, 312,   2, 313,  62,  63,   3, 314, 315]]) tensor([[316]])
tensor([[ 10, 308,   3, 309, 310]]) tensor([[311]])
tensor([[  1,   2,   3, 234,   5, 235]]) tensor([[131]])
tensor([[  1,   2,   3, 103,   5, 104,  19, 105]]) tensor([[106]])
tensor([[  1,   2,   3, 212,   5,  14, 213, 214]]) tensor([[215]])
tensor([[  1,   2,   3, 141, 117,  83,   3, 277, 278]]) tensor([[121]])
tensor([[10, 96,  3, 97]]) tensor([[98]])
tensor([[  1,   2,   3, 146, 147,  19, 148]]) tensor([[149]])
tensor([[ 78,  79, 288,  81,  19,  14, 289]]) tensor([[85]])
tensor([[ 1,  2,  3, 17, 18, 19, 20, 21, 22]]) tensor([[23]])
tensor([[ 42, 101,   2,   3,  17]]) tensor([[102]])
tensor([[ 10, 140,   3, 141, 142,  12, 143,  83,   3, 144]]) tensor([[145]])
tensor([[  1,   2,   3,  69,   5, 155]]) tensor([[156]])
tensor([[ 10,  29, 130, 131]]) tensor([[132]])
tensor([[ 10, 140,   3, 141, 270,  93, 271,   5,   3, 272]]) tensor([[273]])
tensor([[ 10,  75, 208]]) tensor([[209]])
tensor([[ 10,  96,   3, 104, 239]]) tensor([[240]])
tensor([[  1,   2,   3, 180, 181, 182, 183]]) tensor([[184]])
tensor([[10, 29,  3, 30, 31]]) tensor([[32]])
tensor([[ 42,  86,  87, 241, 242,  19,  39, 243]]) tensor([[244]])
tensor([[ 10,  11, 189, 158, 190]]) tensor([[191]])
tensor([[ 1,  2,  3,  4,  5, 99]]) tensor([[100]])
tensor([[10,  2,  3, 66,  5, 67]]) tensor([[68]])
tensor([[ 42,   2,   3, 274, 211, 275]]) tensor([[276]])
tensor([[  1,   2,   3, 146,  86,  19, 192, 193]]) tensor([[194]])
tensor([[10, 55,  3, 56,  5, 57]]) tensor([[58]])
tensor([[  1,   2,   3, 122, 123,  19,   3,  45]]) tensor([[124]])
tensor([[  1,   2,   3,   4,   5, 279]]) tensor([[280]])
tensor([[  1,   2,   3,   4,   5, 236, 237]]) tensor([[238]])
tensor([[ 42, 107,   2, 108,  19, 109]]) tensor([[110]])
tensor([[1, 2, 3, 4, 5, 6]]) tensor([[7]])
tensor([[ 1,  2,  3, 37, 38, 39, 40]]) tensor([[41]])
tensor([[ 42, 174,   2,  62,  39, 175, 176,  12, 177, 178]]) tensor([[179]])
tensor([[ 1,  2,  3, 92, 93, 94]]) tensor([[95]])
tensor([[ 42, 216, 118, 217, 218,  19,  14, 219,  43]]) tensor([[220]])
tensor([[ 42, 137,   2, 226,  12,   3, 227, 228]]) tensor([[155]])
tensor([[ 1,  2,  3,  4,  5, 53]]) tensor([[54]])
tensor([[ 42, 200,   2,  14, 201, 202, 203, 204]]) tensor([[205]])
tensor([[ 42,   2,   3, 210, 137, 168, 211, 169]]) tensor([[113]])
tensor([[ 42, 117, 118,   3, 119,  94, 120]]) tensor([[121]])
tensor([[ 1,  2,  3, 59, 25,  5, 26, 19, 60]]) tensor([[61]])
tensor([[  1,   2,   3,  37, 133,   5,  26]]) tensor([[134]])
tensor([[ 10,  75, 111]]) tensor([[112]])
tensor([[42, 18,  2, 62, 63,  3, 64, 18]]) tensor([[65]])
tensor([[78, 79, 80, 81, 82, 83, 84]]) tensor([[85]])
tensor([[ 78,  79, 261, 151,  14, 262, 153]]) tensor([[36]])
tensor([[ 1,  2,  3, 69,  5, 53]]) tensor([[260]])
tensor([[  1,   2,   3,   4,   5, 286]]) tensor([[287]])
tensor([[10, 75, 76]]) tensor([[77]])
tensor([[  1,   2,   3, 163, 164, 165,  83,  84]]) tensor([[166]])
tensor([[  1,   2,   3,  92, 137,  19,   3,  45]]) tensor([[185]])
tensor([[ 42, 299, 300, 118,  14, 301, 302, 158, 303, 304, 305, 306]]) tensor([[307]])
tensor([[ 1,  2,  3, 69,  5,  3, 70, 71]]) tensor([[72]])
tensor([[ 10,  75,   3, 296,  19, 297]]) tensor([[298]])
tensor([[42, 86, 87, 88, 89, 39, 90]]) tensor([[91]])
tensor([[  1,  87, 229, 230, 231, 232]]) tensor([[233]])
tensor([[ 42, 137,   2,  62,  39,   3, 322, 323]]) tensor([[6]])
tensor([[  1,   2,   3,  33,  34,   5, 245]]) tensor([[246]])

In [26]:
import torch.nn as nn

In [39]:
class VrajRNN(nn.Module):

  def __init__(self, vocab_size):
    super().__init__()
    self.embedding = nn.Embedding(vocab_size, embedding_dim=50) # embedding_dim is hyperparameter
    self.rnn = nn.RNN(50, 64, batch_first=True)  # need batch_first in rnn's -> this is to get the dims as [1,1,vocab_size] cuz it's now output layer time
    self.fc = nn.Linear(64, vocab_size)

  def forward(self, question):
    embedded_question = self.embedding(question)
    hidden, final = self.rnn(embedded_question)
    output = self.fc(final.squeeze(0)) # this is to remove one extra dim

    return output

The reason we did not use sequential layer in the above cell is because of the way rnn works internally.


by default, sequential is designed in a way, that it sends the output of one layer to the very next layer and so and so. and sequential only allows each layer to output one output.


but in rnn, it also output's the intermediate states along with the final output. because it works on timesteps, if there are 5 works in the data, it will output 6 different tensors which have 5 of those intermediate stps and the 6th one is the final  one. so the intermediate ones are the output of hidden states while the final last one is the final output that we are looking for and which will be used by the next layer

so since the output from the nn.RNN will have a total of 6 (for example) tensors, we will only send the last one. but for this, we will have to write it manually. so we will modify the forward() functino

In [44]:
learning_rate = 0.001
epochs=50

In [45]:
model = VrajRNN(len(vocab))

In [46]:
criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(), lr = learning_rate)

In [49]:
# training loop
for epoch in range(epochs):

  total_loss = 0

  for question, answer in dataloader:

    # clearing gradients
    optimizer.zero_grad()

    # forward pass
    output = model(question)

    # loss
    loss = criterion(output, answer[0])

    # calculate gradients
    loss.backward()

    # update gradients
    optimizer.step()

    total_loss = total_loss + loss.item()

  print(f"Epoch {epoch+1}, Loss: {total_loss:4f}")

Epoch 1, Loss: 0.077944
Epoch 2, Loss: 0.074514
Epoch 3, Loss: 0.071115
Epoch 4, Loss: 0.067952
Epoch 5, Loss: 0.064906
Epoch 6, Loss: 0.062113
Epoch 7, Loss: 0.059227
Epoch 8, Loss: 0.056564
Epoch 9, Loss: 0.054066
Epoch 10, Loss: 0.051645
Epoch 11, Loss: 0.049349
Epoch 12, Loss: 0.047113
Epoch 13, Loss: 0.045019
Epoch 14, Loss: 0.043022
Epoch 15, Loss: 0.041110
Epoch 16, Loss: 0.039308
Epoch 17, Loss: 0.037580
Epoch 18, Loss: 0.035884
Epoch 19, Loss: 0.034330
Epoch 20, Loss: 0.032796
Epoch 21, Loss: 0.031340
Epoch 22, Loss: 0.029961
Epoch 23, Loss: 0.028662
Epoch 24, Loss: 0.027361
Epoch 25, Loss: 0.026157
Epoch 26, Loss: 0.025018
Epoch 27, Loss: 0.023908
Epoch 28, Loss: 0.022857
Epoch 29, Loss: 0.021845
Epoch 30, Loss: 0.020892
Epoch 31, Loss: 0.019986
Epoch 32, Loss: 0.019076
Epoch 33, Loss: 0.018254
Epoch 34, Loss: 0.017446
Epoch 35, Loss: 0.016680
Epoch 36, Loss: 0.015958
Epoch 37, Loss: 0.015253
Epoch 38, Loss: 0.014598
Epoch 39, Loss: 0.013942
Epoch 40, Loss: 0.013338
Epoch 41, Loss: 0.012761
Epoch 42, Loss: 0.012205
Epoch 43, Loss: 0.011664
Epoch 44, Loss: 0.011158
Epoch 45, Loss: 0.010667
Epoch 46, Loss: 0.010213
Epoch 47, Loss: 0.009759
Epoch 48, Loss: 0.009329
Epoch 49, Loss: 0.008924
Epoch 50, Loss: 0.008531

In [52]:
def predict_answer(model, question, threshold=0.5):

  # convert question to numbers
  numerical_question = text_to_indices(question, vocab)

  # tensor
  question_tensor = torch.tensor(numerical_question).unsqueeze(0)

  # send to model
  output = model(question_tensor)

  # convert logits to probs
  probs = torch.nn.functional.softmax(output, dim=1)

  # find index of max probability
  value, index = torch.max(probs, dim=1)

  if value < threshold:
    print("idk bruvv :*(")
  else:
    print(list(vocab.keys())[index])

In [54]:
predict_answer(model, "What is the capital of india?")

delhi

In [55]:
predict_answer(model, "What is delhi?")

idk bruvv :*(